#-----------------------------------------------------------------------
#
#   util.properties 
#
#-----------------------------------------------------------------------


logicalPath=http://10.53.0.20/upload/
streamPath=http://localhost:9090/streamdocs/custom/viewer
#logicalPath=http://220.126.231.124:28180/upload/

qrPath=/home/wmss/upload/qrCode/


uploadPath=/home/wmss/upload/
downloadPath=/home/wmss/download/

equipPath=D:/projectFiles/equip/
smartDataPath=D:/projectFiles/smartData/
imagePath=/home/wmss/upload/imageShare/

drawPath=/home/wmss/upload/draws
docPath=/home/wmss/upload/docs


mobileServerIp=10.53.0.20
mobilePdfIp=10.53.0.20

eaiURL=http://10.53.2.201:30001/ws/
#eaiURL=http://10.53.2.201:30002/ws/

docEaiURL=http://10.53.2.201:30003/ws/
#docEaiURL=http://10.53.2.201:30004/ws/

#mobileServerIp=220.126.231.124:28180
#mobilePdfIp=220.126.231.124:28180

syncSvIp=http://192.168.100.132:8088

WMSS_eaiURL=http://10.145.1.43:5030/ws/

# =============== MPPS =============== 
WMSS_URL=http://wmss.khnp.se.hn
OZ_HOME=http://10.53.2.23:18080/oz80
MPPS_DIR=E:/mpps
