#-----------------------------------------------------------------------
#
#   util.properties 
#
#-----------------------------------------------------------------------


logicalPath=http://10.53.0.21/upload/
streamPath=http://10.53.2.22:8888/streamdocs/custom/viewer
#logicalPath=http://220.126.231.124:28180/upload/

#Not used
mobileServerIp=10.53.0.21
mobilePdfIp=10.53.0.21

#eaiURL=http://10.53.2.201:30001/ws/
eaiURL=http://10.53.2.201:30012/ws/

#docEaiURL=http://10.53.2.201:30003/ws/
docEaiURL=http://10.53.2.201:30013/ws/

#mobileServerIp=220.126.231.124:28180
#mobilePdfIp=220.126.231.124:28180

# =============== WMSS =============== 

WMSS_eaiURL=http://10.145.1.43:5030/ws/

# =============== PELS ===============
WMSS_URL=http://wmss.khnp.se.hn
OZ_HOME=http://10.53.2.23:18080/oz80

PELS_DIR=C:/PELS
PELS_URL=http://pels.khnp.se.hn
PELS_IP_URL=http://localhost:8080

ECAP_URL=http://10.53.2.201:9007
#WMSS_URL=http://10.53.2.22:18080
# 10.135.1.31