/**
 * 유틸리티 통합 내보내기
 */

export * from './helpers.ts';
export {
  caseConversions,
  cleanAmount,
  cleanStringArray,
  compareStrings,
  compressString,
  createSearchKey,
  escapeRegex,
  expandString,
  getStringStats,
  groupByFirstLetter,
  highlightSearch,
  htmlEscape,
  htmlUnescape,
  includesIgnoreCase,
  isValidString,
  limitString,
  maskEmail,
  maskPhone,
  normalizeWhitespace,
  paddingAndTruncate,
  processTemplate,
  removeAccents,
  removeStrings,
  replaceAll,
  replaceFirst,
  replaceRegex,
  safeCompare,
  safeGetString,
  safeStringify,
  searchInStrings,
  splitString,
  transformString,
  wordTokens,
  // 데이터 Map (Object) , List 변형가공 (예 > API 데이터 처리를 위해 데이터 재생성)
  objectToArray,
  arrayToObject,
  extractFields,
  extractAndTransform,
  deepClone,
  groupAndAggregate,
  removeDuplicates,
  sortData,
  sortDataMultiple,
  filterData,
  processData,
  createApiRequestBody,
  generateStatistics,
  findData,
  hasData,
  countData,
  mergeData,
  paginateData,
} from './lodashUtils.ts';
export * from './logger.ts';
export {
  calculateBusinessDays,
  calculateBusinessDaysDiff,
  calculateExpiration,
  calculateTimeDiff,
  checkTimeRange,
  convertTimezone,
  filterByDateRange,
  formatTime as formatMomentTime,
  getCalendarDisplay,
  getCountdown,
  getCurrentMoment,
  getCurrentTimeString,
  getDaysBetween,
  getHumanizedTime,
  getPeriodBoundaries,
  getRelativeTime,
  isValidDate,
  normalizeTime,
  safeFormat,
} from './momentUtils.ts';
export {
  checkForUpdates,
  compareVersions,
  formatVersion,
  getAppVersion,
  getVersionAsJson,
  getVersionBadgeColor,
  isVersionGreater,
  isVersionInRange,
  isVersionLower,
  logVersionInfo,
  parseVersion,
  useAppVersion,
} from './versionUtils.ts';
export {
  calculateCompatibilityScore,
  compareBrowserInfo,
  filterBrowserInfo,
  formatBrowserInfo,
  getBrowserInfo,
  getBrowserInfoAsJson,
  logBrowserInfo,
  watchBrowserChanges,
} from './browserUtils.ts';
export {
  checkNetworkConnection,
  createNetworkWatcher,
  formatNetworkState,
  getNetworkQuality,
  getNetworkQualityBadgeColor,
  getNetworkQualityColor,
  getNetworkStateAsJson,
  logNetworkState,
  testNetworkQuality,
  useNetworkMonitoring,
  validateNetworkBeforeSend,
} from './networkUtils.ts';
