#-----------------------------------------------------------------------
#
#   db.properties 
#
#-----------------------------------------------------------------------

#MSSQL
#jdbc.driverClass=com.microsoft.sqlserver.jdbc.SQLServerDriver
#jdbc.url=jdbc:sqlserver://220.126.231.124:1433;databaseName=mdrcoservice_khnp
#jdbc.username=khnp
#jdbc.password=khnp123!@#
#jdbc.username=kepco
#jdbc.password=neodreams00

#ORACLE(\uc678\ubd80)
jdbc.driverClassOracle=oracle.jdbc.driver.OracleDriver
jdbc.urlOracle=jdbc:oracle:thin:@220.126.231.124:1521:wmss
jdbc.usernameOracle=khnp
jdbc.passwordOracle=neodreams00