#-----------------------------------------------------------------------
#
#   util.properties 
#
#-----------------------------------------------------------------------


logicalPath=http://10.53.0.20/upload/
streamPath=http://192.168.100.132:9090/streamdocs/custom/viewer
#logicalPath=http://220.126.231.124:28180/upload/

qrPath=/home/wmss/upload/qrCode/


uploadPath=/home/wmss/upload/
downloadPath=/home/wmss/download/

equipPath=D:/projectFiles/equip/
smartDataPath=D:/projectFiles/smartData/
imagePath=/home/wmss/upload/imageShare/


drawPath=d:/home/wmss/upload/draws
docPath=d:/home/wmss/upload/docs


mobileServerIp=10.53.0.20
mobilePdfIp=10.53.0.20

WMSS_eaiURL=http://10.145.1.43:5030/ws/

# =============== MPPS =============== 
WMSS_URL=http://wmss.khnp.se.hn
OZ_HOME=http://localhost:7070/oz80
MPPS_DIR=E:/mpps
