#-----------------------------------------------------------------------
#
#   util.properties 
#
#-----------------------------------------------------------------------


logicalPath=http://10.53.0.21/upload/
streamPath=http://10.53.2.22:8888/streamdocs/custom/viewer
#logicalPath=http://220.126.231.124:28180/upload/

#Not used
mobileServerIp=10.53.0.21
mobilePdfIp=10.53.0.21

#eaiURL=http://10.53.2.201:30001/ws/
eaiURL=http://10.53.2.201:30012/ws/

#docEaiURL=http://10.53.2.201:30003/ws/
docEaiURL=http://10.53.2.201:30013/ws/

#mobileServerIp=220.126.231.124:28180
#mobilePdfIp=220.126.231.124:28180


WMSS_eaiURL=http://10.145.1.43:5030/ws/

# =============== MPPS =============== 
WMSS_URL=http://wmss.khnp.se.hn
OZ_HOME=http://10.53.2.23:18080/oz80
MPPS_DIR=E:/mpps

# Production \uC740 empty \uC0AC\uC2E4 \uC5C6\uC5B4\uB3C4 \uB41C\uB2E4. local \uC5D0\uC11C\uB9CC \uC0AC\uC6A9\uD558\uB2C8\uAE4C \uC77C\uB2E8 \uD788\uC2A4\uD1A0\uB9AC\uC0C1\uC73C\uB85C \uC720\uC9C0
# PELS_ELINK_V2_BASE_URL=
